# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push

jobs:
  lint:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run eslint > eslint-output
      - name: Save eslint-output
        uses: actions/upload-artifact@v2
        with:
          name: eslint-result
          path: ./eslint-output

  test:
    needs: lint
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: yarn test > jest-output
      - name: Save coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage
      - name: Save jest-result
        uses: actions/upload-artifact@v2
        with:
          name: jest-result
          path: ./jest-output
